language: node_js
env:
    global:
        - NODEVER=10.15.2
        - RUBYVER=2.5.3
        - xcodeVer=xcode10.1
        - LinDistro=xenial
        - GCCVER=4.9
        - arch=x64
        - mode=release
        - NODEC_TESTS_TMPDIR=/tmp/nodec_tests_tmpdir
        - LINPRJDIR=/home/travis/build/slee047/node-packer
        - OSXPRJDIR=/Users/travis/build/slee047/node-packer
matrix:
  include:
  - os: osx
    osx_image: $xcodeVer
    node_js: $NODEVER
    env: TEST_SCRIPT=coffeescript_1
  - os: linux
    dist: $LinDistro
    node_js: $NODEVER
    env: TEST_SCRIPT=coffeescript_1
  - os: osx
    osx_image: $xcodeVer
    node_js: $NODEVER
    env: TEST_SCRIPT=coffeescript_2
  - os: linux
    dist: $LinDistro
    node_js: $NODEVER
    env: TEST_SCRIPT=coffeescript_2
  - os: osx
    osx_image: $xcodeVer
    node_js: $NODEVER
    env: TEST_SCRIPT=microtime
  - os: linux
    dist: $LinDistro
    node_js: $NODEVER
    env: TEST_SCRIPT=microtime
before_install:
  # Cache is limited to 1GB, so forget about caching homebrew or temp directories.
  # Do NOT attempt to skip dependency check, or it will fail.
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install "gcc-$GCCVER" "g++-$GCCVER" nasm squashfs-tools; fi
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
  homebrew:
    packages:
        - ruby@2.5
        - squashfs
        - openssl
        - nasm
install:
#LD_LIBRARY_PATH / DYLD_LIBRARY_PATH contains only darwin-x64, linux-arm, linux-x64 and win32
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export PRJROOT_DIR="$OSXPRJDIR"; export DYLD_LIBRARY_PATH="$PRJROOT_DIR/node/node_modules/microtime/prebuilds/darwin-x64;$DYLD_LIBRARY_PATH"; clang --version; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export PRJROOT_DIR="$LINPRJDIR"; export CXX="g++-$GCCVER" CC="gcc-$GCCVER"; export LD_LIBRARY_PATH="$PRJROOT_DIR/node/node_modules/microtime/prebuilds/linux-x64;$LD_LIBRARY_PATH"; "gcc-$GCCVER" --version; "g++-$GCCVER" --version; fi
  - mkdir -p $NODEC_TESTS_TMPDIR
  - git clone --depth 1 https://github.com/jashkenas/coffeescript.git
before_script:
  - python --version
  - nasm -v
  - mksquashfs -version
  - ruby --version
  - node --version
  - npm --version
  - cd node
  - npm install microtime
  - cd $PRJROOT_DIR
script:
  - ruby tests/$TEST_SCRIPT || exit $?