version: '{build}'

image: 
- Visual Studio 2017
environment:
  DEPEND_DIR: C:\dependencies
  PRJROOT_DIR: C:\projects\node-packer
  NODEC_TESTS_TMPDIR: C:\tmp
  NODEC_NODE: 10.15.2
  GYP_MSVS_VERSION: 2017
  mode: release
  arch: x64
  matrix:
    - TEST_SCRIPT: coffeescript_1
    - TEST_SCRIPT: coffeescript_2
    - TEST_SCRIPT: microtime
cache:
  - node_modules
  - ../../dependencies -> appveyor.yml

build_script:
- ps: |
    $ErrorActionPreference="Stop"

    mkdir $env:NODEC_TESTS_TMPDIR

    mkdir $env:DEPEND_DIR

    $depBin = Join-Path $env:DEPEND_DIR -ChildPath 'usr' | Join-Path -ChildPath 'bin'
    if (Test-Path($depBin)) 
    {
        Write-Host 'Skipping Ruby as cache is present.' -ForegroundColor Yellow
    } else{
        Start-FileDownload https://raw.githubusercontent.com/slee047/node-packer/AppVeyorDeps/ruby.zip -FileName $env:DEPEND_DIR\ruby.zip

        Start-FileDownload https://github.com/pmq20/squashfuse/files/691217/sqfs43-win32.zip -FileName $env:DEPEND_DIR\sqfs43-win32.zip

        Start-FileDownload https://nodejs.org/dist/v$env:NODEC_NODE/node-v$env:NODEC_NODE-win-$env:arch.zip -FileName $env:DEPEND_DIR\node.zip

        Start-FileDownload https://raw.githubusercontent.com/slee047/node-packer/AppVeyorDeps/nasm.zip -FileName $env:DEPEND_DIR\nasm.zip

        Add-Type -AssemblyName System.IO.Compression.FileSystem

        [System.IO.Compression.ZipFile]::ExtractToDirectory("$env:DEPEND_DIR\ruby.zip", "$env:DEPEND_DIR")

        [System.IO.Compression.ZipFile]::ExtractToDirectory("$env:DEPEND_DIR\sqfs43-win32.zip", "$env:DEPEND_DIR\usr\bin")

        [System.IO.Compression.ZipFile]::ExtractToDirectory("$env:DEPEND_DIR\node.zip", "$env:DEPEND_DIR\usr\bin")

        [System.IO.Compression.ZipFile]::ExtractToDirectory("$env:DEPEND_DIR\nasm.zip", "$env:DEPEND_DIR")
    }

test_script:
- cmd: |
    set PATH=%DEPEND_DIR%\node-v%NODEC_NODE%-win-%arch%;%DEPEND_DIR%\usr\bin;%PATH%

    npm install npm-cli -g

    python --version

    mksquashfs -version

    ruby --version

    node --version

    nasm -v

    npm --version

    cd node-packer

    git clone --depth 1 https://github.com/jashkenas/coffeescript.git & exit 0

    ruby tests\%TEST_SCRIPT%